[tool.poetry]
name = "chivita-proyect"
version = "0.1.0"
description = ""
authors = ["Sofia-Sonia-Martinez <sofiasoniamar99@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
